# Generated by Django 3.2.5 on 2021-08-01 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actions', '0002_action_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('block_prev_hash', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('block_prev', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='block.block')),
                ('data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actions.action')),
                ('signers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
