# Generated by Django 3.2.5 on 2021-08-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
